#
# Copyright (c) 2019-2026 0xACE8
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/0xACE8
#
# Description: A modular, privacy-focused OpenWrt build pipeline powered by GitHub Actions.
# èª¬æ˜: GitHub Actionsã®ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«åŒ–ã‚’æ´»ç”¨ã—ã€ãƒ—ãƒ©ã‚¤ãƒã‚·ãƒ¼ã¨ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã‚’ç¢ºä¿ã—ãŸOpenWrtãƒ“ãƒ«ãƒ‰ã€‚
#

name: Build cmcc_xr30-emmc ponly 24.10 kernel 6.6 actions.

on:
  workflow_dispatch:
    inputs:
      restore_config:
        description: 'Restore Configuration ğŸ‡¯ğŸ‡µ è¨­å®šã‚’å¾©å…ƒ'
        type: boolean
        default: false
      telegram_notify:
        description: 'Telegram Notification ğŸ‡¯ğŸ‡µ Telegramé€šçŸ¥'
        type: boolean
        default: false
      upload_firmware:
        description: 'Upload to Artifactsã€€ ğŸ‡¯ğŸ‡µ Artifactã«ä¿å­˜'
        type: boolean
        default: false
      upload_release:
        description: 'Upload to Releaseã€€ã€€ ğŸ‡¯ğŸ‡µ Releaseã«å…¬é–‹'
        type: boolean
        default: false
#  schedule:
#    - cron: '0 19 * * 0'

env:
  # annawrt 2410
  PONLY2410_K66_REPO_LINK:              ${{ secrets.PONLY2410_K66_REPO_LINK }}
  PONLY2410_K66_REPO_TREE:              ${{ secrets.PONLY2410_K66_REPO_TREE }}
  PONLY2410_K66_REPO_DIFF:              ${{ secrets.PONLY2410_K66_REPO_DIFF }}
  # cmcc-xr30-emmc
  CMCC_XR30_EMMC_PONLY2410_K66_PATCHES: ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_PATCHES }}
  CMCC_XR30_EMMC_PONLY2410_K66_PROFILE: ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_PROFILE }}
  CMCC_XR30_EMMC_PONLY2410_K66_ARCHIVE: ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_ARCHIVE }}
  # access token
  ACCESS_TOKEN:                         ${{ secrets.ACCESS_TOKEN }}
  # feeds source
  ADD_EXTRA_SOURCE:                     ${{ secrets.ADD_EXTRA_SOURCE }}
  # check sha512sum
  ACCESS_SHA512SUM:                     ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_REPACKAGE:                     ${{ secrets.ACCESS_REPACKAGE }}
  # cmcc color sytle for argon
  ARGON_THEME_CMCC:                     ${{ secrets.ARGON_THEME_CMCC }}
  # telegram bot
  TELEGRAM_BOT_KEY:                     ${{ secrets.TELEGRAM_BOT_KEY }}
  TELEGRAM_CHAT_ID:                     ${{ secrets.TELEGRAM_CHAT_ID }}
  # hardware & repo info
  DEVICE_NAME:                          CMCC_XR30-EMMC
  TARGET_CHIP:                          mt7981b
  TARGET_DISK:                          8GB_eMMC
  SOURCE_CODE:                          padavanonly
  KERNEL_VERS:                          kernel_6.6
  OUTPUT_FILE:                          annawrt-24.10-k6.6-ace-mt7981b-cmcc_xr30-emmc-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: Checkout (ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Before freeing up disk space (ãƒ‡ã‚£ã‚¹ã‚¯ã‚¹ãƒšãƒ¼ã‚¹ã‚’è§£æ”¾ã™ã‚‹å‰ã«)
      run: |
        echo "ãƒ‡ã‚£ã‚¹ã‚¯ã‚¹ãƒšãƒ¼ã‚¹ã‚’è§£æ”¾ã™ã‚‹å‰ã«"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: "Optimize Disk Space (ãƒ‡ã‚£ã‚¹ã‚¯ã‚¹ãƒšãƒ¼ã‚¹ã®æœ€é©åŒ–)"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: Freeing up disk space (ãƒãƒ¼ãƒ‰ãƒ‰ãƒ©ã‚¤ãƒ–ã®ç©ºãå®¹é‡ã‚’å¢—ã‚„ã™)
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 8192
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Check Server Performance (ã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã‚’ç¢ºèªã™ã‚‹)
      run: |
        echo "âš ï¸è­¦å‘Šã™ã‚‹âš ï¸"
        echo "å‰²ã‚Šå½“ã¦ã‚‰ã‚ŒãŸã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«ã¯åˆ¶é™ãŒã‚ã‚Šã¾ã™ã€‚ãƒ—ãƒ©ã‚°ã‚¤ãƒ³ã‚’é¸æŠã—ã™ãã‚‹å ´åˆã¯ã€CPU ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«æ³¨æ„ã—ã¦ãã ã•ã„ã€‚"
        echo -e "æ—¢çŸ¥ã®CPUãƒ¢ãƒ‡ãƒ«ï¼ˆé™é †ï¼‰: 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "-------------------------CPU æƒ…å ±---------------------------"
        echo "CPUã®ç‰©ç†æ•°  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUã‚³ã‚¢æ•°    : $(nproc)"
        echo -e "CPUãƒ¢ãƒ‡ãƒ«æƒ…å ±:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "------------------------ãƒ¡ãƒ¢ãƒªæƒ…å ±--------------------------"
        echo "ãƒ¡ãƒ¢ãƒªã®è©³ç´°:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "---------------------ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯æƒ…å ±---------------------"
        echo "ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯å®¹é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization environment (åˆæœŸåŒ–ç’°å¢ƒ)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq full-upgrade
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt -yqq install cargo
        rustup target add aarch64-unknown-linux-musl
        sudo -E systemctl daemon-reload
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE

    - name: Setup Git Credentials
      run: |
        git config --global url."https://$ACCESS_TOKEN@github.com/0xACE8/".insteadOf "https://github.com/0xACE8/"
        
    - name: Clone source code (ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã®ã‚¯ãƒ­ãƒ¼ãƒ³)
      working-directory: ./
      run: |
        df -hT $PWD
        git clone $PONLY2410_K66_REPO_LINK: -b $PONLY2410_K66_REPO_TREE openwrt
        cd openwrt
        ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_PATCHES }}
        echo "CMCC_XR30_EMMC_PONLY2410_K66_PATCH done."
        ${{ secrets.ADD_EXTRA_SOURCE }}
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

        # Remove All China download sources (ä¸­å›½ã‹ã‚‰ã®ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã‚½ãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Generate Variables (å¤‰æ•°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        SOURCE_REPO="$(echo $PONLY2410_K66_REPO_LINK: | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV

    - name: Cache Toolchain (ã‚­ãƒ£ãƒƒã‚·ãƒ¥ãƒ„ãƒ¼ãƒ«ãƒã‚§ãƒ¼ãƒ³)
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: MT7981b-${{ env.SOURCE_CODE }}-${{ env.SOURCE_REPO }}-${{ env.KERNEL_VERS }}-${{ secrets.PONLY2410_K66_REPO_BRANCH }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: Updata & install feeds (ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆã¨ãƒ•ã‚£ãƒ¼ãƒ‰ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«)
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/sbwml/packages_lang_golang -b 25.x feeds/packages/lang/golang
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Load custom configuration (ã‚«ã‚¹ã‚¿ãƒ æ§‹æˆã‚’èª­ã¿è¾¼ã‚€)
      working-directory: ./openwrt
      run: |
        ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_PROFILE }}
        echo "load config done."
        ${{ secrets.PONLY2410_K66_REPO_DIFF }}
        echo "load repo patch done."
        ${{ secrets.ARGON_THEME_CMCC }}
        echo "load theme done."

    - name: Restore configuration archive (ãƒãƒƒã‚¯ã‚¢ãƒƒãƒ—ã—ãŸæ§‹æˆã‚¢ãƒ¼ã‚«ã‚¤ãƒ–ã‚’å¾©å…ƒã™ã‚‹)
      if: (github.event.inputs.restore_config == 'true' && github.event.inputs.restore_config != 'false') || contains(github.event.action, 'restore_config') && !cancelled()
      working-directory: ./openwrt
      run: |
        rm -rf files
        ${{ secrets.CMCC_XR30_EMMC_PONLY2410_K66_ARCHIVE }}
        echo "load config backup done."
        echo "OUTPUT_FILE=annawrt-24.10-k6.6-ace-mt7981b-cmcc_xr30-emmc-configured-sysupgrade" >> $GITHUB_ENV

    - name: Boost Wi-Fi 5G signal to 25dbm (Wi-Fi 5Gä¿¡å·ã‚’25dbmã¾ã§ãƒ–ãƒ¼ã‚¹ãƒˆ)
      working-directory: ./openwrt
      run: |
        ${{ secrets.BOOST_5G_TO_25DBM }}

    - name: Download package (ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰)
      working-directory: ./openwrt
      id: package
      run: |
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware (ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã‚’ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã™ã‚‹)
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upgrading variables (å¤‰æ•°ã®ã‚¢ãƒƒãƒ—ã‚°ãƒ¬ãƒ¼ãƒ‰)
      run: |
        echo "OUTPUT_FILE=${OUTPUT_FILE}_${FILE_DATE}" >> $GITHUB_ENV

    - name: View Disk Usage (ãƒ‡ã‚£ã‚¹ã‚¯ä½¿ç”¨é‡ã®è¡¨ç¤º)
      if: (!cancelled())
      run: df -hT

    - name: Telegram notify when compilation error (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã‚¨ãƒ©ãƒ¼ãŒç™ºç”Ÿã—ãŸã¨ãã«ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status != 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled()
      env:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_KEY }}
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_KEY }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âŒ%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã«å¤±æ•—ã—ã¾ã—ãŸï¼%20âŒ%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.TARGET_DISK }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ§¿ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨:%0Aã€€%20ã€€${{ env.KERNEL_VERS }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ”€ãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.PONLY2410_K66_REPO_TREE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»âŒã‚¨ãƒ©ãƒ¼ã®æ™‚é–“:%0Aã€€%20ã€€$(date +'%Yå¹´%mæœˆ%dæ—¥_%Hæ™‚%Måˆ†')%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Organize files (ãƒ•ã‚¡ã‚¤ãƒ«ã‚’æ•´ç†ã™ã‚‹)
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls | grep -v *sysupgrade.bin | xargs rm -rdf
        mv *.bin ${{ env.OUTPUT_FILE }}.bin
        sha512sums ${{ secrets.ACCESS_SHA512SUM }} sha512sums ${{ env.OUTPUT_FILE }}.bin
        ${{ secrets.ACCESS_REPACKAGE }} ${{ env.OUTPUT_FILE }}.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Artifact (Artifactã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_firmware == 'true' && github.event.inputs.upload_firmware  != 'false') || contains(github.event.action, 'upload_firmware') && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILE }}
        path: ${{ env.FIRMWARE }}

    - name: Telegram notify when compilation complete (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ãŸã‚‰ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled()
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_KEY }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âœ…%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ã¾ã—ãŸï¼%20âœ…%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.TARGET_DISK }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ§¿ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨:%0Aã€€%20ã€€${{ env.KERNEL_VERS }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ”€ãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.PONLY2410_K66_REPO_TREE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ãƒ•ã‚¡ã‚¤ãƒ«åå‰:%0Aã€€%20ã€€${{ env.OUTPUT_FILE}}%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Generate Release Tag (ã‚¿ã‚°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        RELEASE_TAG="$TARGET_CHIP-$DEVICE_NAME-$TARGET_DISK-$KERNEL_VERS-$FILE_DATE"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Upload Firmware To Release (ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã‚’ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_release == 'true' && github.event.inputs.upload_release  != 'false') || contains(github.event.action, 'upload_release') && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.TARGET_CHIP }}_${{ env.DEVICE_NAME }}_${{ env.TARGET_DISK }}_${{ env.KERNEL_VERS }}_${{ env.FILE_DATE }}
        allowUpdates: false
        tag: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          **ã“ã®ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã€CPUã€Œ${{ env.TARGET_CHIP }}ã€ãƒ¢ãƒ‡ãƒ«ã€Œ${{ env.DEVICE_NAME }}ã€ã‚’æ­è¼‰ã—ãŸãƒ«ãƒ¼ã‚¿ãƒ¼âœ… ${{ env.TARGET_DISK }} âœ…ã«ã®ã¿é©ã—ã¦ã„ã¾ã™ã€‚**
          ### ğŸ“’ã€Œ${{ env.SOURCE_CODE }}ã€ãƒªãƒã‚¸ãƒˆãƒªã®ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‹ã‚‰ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã€‚
          - ğŸ›œ æ”¯æ´ãƒ‡ãƒã‚¤ã‚¹: ${{ env.DEVICE_NAME }}
          - ğŸ’½ ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯: ${{ env.TARGET_DISK }}
          - ğŸ§¿ ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨: ${{ env.KERNEL_VERS }}
          - ğŸ“ ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰: ${{ env.SOURCE_CODE }}
          - ğŸ“¦ ãƒªãƒã‚¸ãƒˆãƒªã‚’: ${{ env.SOURCE_REPO }}
          - ğŸ”€ ãƒ–ãƒ©ãƒ³ãƒåå‰: ${{ secrets.PONLY2410_K66_REPO_TREE }}
          - ğŸŒ æ¥ç¶šã‚¢ãƒ‰ãƒ¬ã‚¹: 192.168.***.1 ã¾ãŸã¯ ${{ env.SOURCE_CODE }}.lan
          - ğŸ”‘ ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã¯: ãªã—
          ### âš ï¸ è­¦å‘Šã™ã‚‹ âš ï¸
          - â€¼ï¸ç¾åœ¨ã®ãƒªãƒã‚¸ãƒˆãƒªã«ã‚ˆã£ã¦ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã™ã¹ã¦éå…¬é–‹ã§ã‚«ã‚¹ã‚¿ãƒã‚¤ã‚ºã•ã‚Œã¦ã„ã¾ã™ã€‚
          - â›”ï¸å¼·åˆ¶ãƒ•ãƒ©ãƒƒã‚·ãƒ¥â›”ï¸ã«ã‚ˆã£ã¦ãƒ‡ãƒã‚¤ã‚¹ãŒæå‚·ã—ãŸå ´åˆã€ã“ã®ãƒªãƒã‚¸ãƒˆãƒªã¯ãƒ‡ãƒã‚¤ã‚¹ã®æå‚·ã«ã¤ã„ã¦ä¸€åˆ‡è²¬ä»»ã‚’è² ã„ã¾ã›ã‚“ã€‚

    - name: Delete old workflow runs (å¤ã„ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼å®Ÿè¡Œã‚’å‰Šé™¤ã™ã‚‹)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 2

    - name: Delete Old Releases (å¤ã„ãƒªãƒªãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
